# Generated by Django 3.2.6 on 2021-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('homework_num', models.CharField(max_length=125)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted time')),
            ],
            options={
                'verbose_name': 'Домашка',
                'verbose_name_plural': 'Домашки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeWorkManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiu_email', models.EmailField(max_length=254, unique=True, verbose_name='Логин от УИИ')),
                ('aiu_password', models.CharField(max_length=800, verbose_name='Пароль от УИИ')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['-id'],
            },
        ),
    ]
